version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./docker/.env
    environment:
      TZ: America/New_York
    ports:
      - "9222:9222"
